// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyjhrPpAgkuHeKUZvg-eiK2MkjFDKG3kw',
    appId: '1:706264155707:web:cb15f9a6291bd49481be1e',
    messagingSenderId: '706264155707',
    projectId: 'golf-79d6e',
    authDomain: 'golf-79d6e.firebaseapp.com',
    storageBucket: 'golf-79d6e.firebasestorage.app',
    measurementId: 'G-PMRPTMX2XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBovefiKgw9-AOxrQAENilr8dB_EP25WiY',
    appId: '1:706264155707:android:2a5be6b2e7834ef081be1e',
    messagingSenderId: '706264155707',
    projectId: 'golf-79d6e',
    storageBucket: 'golf-79d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_mKRQ12KtYPqHVGClMdiKieRdlJXO6g',
    appId: '1:706264155707:ios:88c58678622799f981be1e',
    messagingSenderId: '706264155707',
    projectId: 'golf-79d6e',
    storageBucket: 'golf-79d6e.firebasestorage.app',
    iosBundleId: 'com.example.golf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc_mKRQ12KtYPqHVGClMdiKieRdlJXO6g',
    appId: '1:706264155707:ios:88c58678622799f981be1e',
    messagingSenderId: '706264155707',
    projectId: 'golf-79d6e',
    storageBucket: 'golf-79d6e.firebasestorage.app',
    iosBundleId: 'com.example.golf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyjhrPpAgkuHeKUZvg-eiK2MkjFDKG3kw',
    appId: '1:706264155707:web:e6bcde919451ac6c81be1e',
    messagingSenderId: '706264155707',
    projectId: 'golf-79d6e',
    authDomain: 'golf-79d6e.firebaseapp.com',
    storageBucket: 'golf-79d6e.firebasestorage.app',
    measurementId: 'G-EV6K2SDVH0',
  );
}
